FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt


# Install watchdog for auto-restart
RUN pip install watchdog

COPY scraper_producer.py .

CMD ["python", "scraper_producer.py"]
